# Generated by Django 2.1.5 on 2021-03-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_task_match_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='processor',
            field=models.CharField(default='github', max_length=16, verbose_name='processor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='match_method',
            field=models.IntegerField(choices=[(0, '模糊匹配'), (1, '精确匹配'), (2, '单词匹配')], default=0),
        ),
    ]
